dist: trusty
sudo: required
language: cpp
os: linux
compiler: gcc
addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
      - g++-8
      - g++-8-multilib
      - cmake
before_install: eval "CC=gcc-8 && CXX=g++-8"
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
deploy:
    provider: releases
    file: SprayFix.so
    skip_cleanup: true
    overwrite: true
    api_key: '$GITHUB_API_KEY'
    on:
      tags: true
